apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
  labels:
    team: dev
spec:
  template:
    metadata:
      name: rs-pod
      labels:
        team: dev
    spec:
      containers:
        - name: rs-container
          image: nginx
  selector:
      matchExpressions:
        - key: team
          operator: In
          values: 
            - dev
            - prod
  replicas: 3
  

