apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc123
spec:
   template:
     metadata:
       name: mypod123
       labels:
         team: dev
     spec:
      containers:
        - name: mycontainer
          image: nginx
   replicas: 4
